### PR TITLE
Improve code style

### PR DESCRIPTION
**Pull request by ritiksr25**
- helper functions for send error and success
- alias for env data
- add .env.example file
- seperate dev and prod environment
- using alias for http codes

### CODE REVIEW

**Comment by ritiksr25** [comment]
> I think there is no need to require status codes utility/helpers.js
It is required because sendError will receive a param, status which will be BAD_REQUEST, etc. and in res.status(status), status will be derived from the alias to get the corresponding code!!

**Comment by ritiksr25** [comment]
> I think there is no need to require status codes utility/helpers.js

It is required because sendError will receive a param, status which will be BAD_REQUEST, etc. and in res.status(status), status will be derived from the alias to get the corresponding code!!

**Comment by rhnmht30** [comment]
> > I think there is no need to require status codes utility/helpers.js
> 
> It is required because sendError will receive a param, status which will be BAD_REQUEST, etc. and in res.status(status), status will be derived from the alias to get the corresponding code!!

Value of BAD_REQUEST will be passed on with the function that will stick to status variable.

**Comment by ritiksr25** [comment]
> > > I think there is no need to require status codes utility/helpers.js
> > 
> > 
> > It is required because sendError will receive a param, status which will be BAD_REQUEST, etc. and in res.status(status), status will be derived from the alias to get the corresponding code!!
> 
> Value of BAD_REQUEST will be passed on with the function that will stick to status variable.

okay, got it!

**Pull request merged**
