### PR TITLE
Certificate Module

### PR DESCRIPTION
**Pull request by rhnmht30**
Features:
- Lead/core can upload certificate pdf with text font and colors.
- Lead/core can generate a pdf preview before uploading the pdf metadata to make sure the certificate design looks good.
- Lead/core can save the certificate pdf file and font file with its metadata on the server if everything looks good on the preview.
- Participants can generate their certificate anytime they want if they have attended the full event and the certificate design is ready on the server.

### CODE REVIEW

**Comment by rhnmht30** [comment]
@goelaakash79 @mayanksh99 
This is for your reference:
- To request the PDF preview with pdf and font file with x,y,size and rgb as query params.
  - here x,y are the coordinates of text on PDF, size is the font-size and rgb is font color
```javascript
axios.post("http://localhost:5000/api/v1/events/certificate/previewname=Rohan%20Mehta&x=476&y=1380&size=120&red=66&green=208&blue=253",dataForm,{
	responseType: "blob", //Force to receive data in a Blob Format
}).then((response) => {
	console.log(response);
	//Create a Blob from the PDF Stream
	const file = new Blob([response.data], { type: "application/pdf" });
	//Build a URL from the file
	const fileURL = URL.createObjectURL(file);
	//Open the URL on new Window
	window.open(fileURL);
}).catch((err) => {
	//since response type is Blog, we need to parse if server sends a JSON resp.
	if (err.request.responseType === "blob" &&
		err.response.data instanceof Blob &&
		err.response.data.type &&
		err.response.data.type.toLowerCase().indexOf("json") !== -1
		) {
			let reader = new FileReader();
			reader.readAsText(err.response.data);
			reader.onload = () => {
					err.response.data = JSON.parse(reader.result);
					console.log(err.response.data);
			};
		}
});
```

- To add the PDF with pdf and font file with x,y,size and rgb as body.
  - here x,y are the coordinates of text on PDF, size is the font-size and rgb is font color
```javascript
 axios.post("http://localhost:5000/api/v1/events/certificate/add/eventid",{dataForm,x,y,size,red,green,blue}).then((response) => {
	console.log(response);
	// simple JSON response
}).catch((err) => console.log(err.response));
```

- To generate the PDF(participant side).
  - here x,y are the coordinates of text on PDF, size is the font-size and rgb is font color
```javascript
axios.get("http://localhost:5000/api/v1/events/certificate/generate/eventid",{
 responseType: "blob", //Force to receive data in a Blob Format
}).then((response) => {
	console.log(response);
	//Create a Blob from the PDF Stream
	const file = new Blob([response.data], { type: "application/pdf" });
	//Build a URL from the file
	const fileURL = URL.createObjectURL(file);
	//Open the URL on new Window
	window.open(fileURL);
}).catch((err) => {
	//since response type is Blog, we need to parse if server sends a JSON resp.
	if (err.request.responseType === "blob" &&
		err.response.data instanceof Blob &&
		err.response.data.type &&
		err.response.data.type.toLowerCase().indexOf("json") !== -1
		) {
			let reader = new FileReader();
			reader.readAsText(err.response.data);
			reader.onload = () => {
					err.response.data = JSON.parse(reader.result);
					console.log(err.response.data);
			};
		}
});
```

**Comment by mayanksh99** [comment]
okay, understood.

**Comment by ritiksr25** [comment]
cool, but if we store all certificates directly on the server, will it affect storage/performance?

**Comment by rhnmht30** [comment]
> cool, but if we store all certificates directly on the server, will it affect storage/performance (later)?

Storage might be an issue, we can shift to AWS s3 later.

**Pull request merged**
